library(rattle)
library(RColorBrewer)
library(rpart)
library(rpart.plot)
tree <- rpart(formula = num ~ . , data = train, method="class")
treePred <- predict(tree, test, type = "class")
fancyRpartPlot(tree)
print(eval(treePred,test$num))
accDT<-eval(treePred,test$num)